apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/projects-manager: "true"
        io.kompose.service: mongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: agisit023
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: mongo
        imagePullPolicy: ""
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - name: "init-database"
          mountPath: "/docker-entrypoint-initdb.d/"
        - name: mongo-db-volume
          mountPath: /data/db

      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongo-db-volume
        persistentVolumeClaim:
          claimName: mongodb-storage
      - name: "init-database"
        configMap:
          name: create-mongodb-configmap1
status: {}
