apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: project
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: project
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/projects-manager: "true"
        io.kompose.service: project
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: mongodb://project:UenbhkDgE1sSUkyQUE8@mongo:27017/agisit023?directConnection=true
        image: ffiaesist/pm-project:1.0.0
        imagePullPolicy: ""
        name: project
        ports:
        - containerPort: 3019
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
