apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: task
  name: task
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: task
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/projects-manager: "true"
        io.kompose.service: task
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: mongodb://task:zYXm7HJNpsNPsTBte4@mongo:27017/agisit023?directConnection=true
        image: ffiaesist/pm-task:1.0.0
        imagePullPolicy: ""
        name: task
        ports:
        - containerPort: 3020
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
