apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: user
  name: user
spec:
  ports:
  - name: "3021"
    port: 3021
    targetPort: 3021
  selector:
    io.kompose.service: user
status:
  loadBalancer: {}
